// <auto-generated>
// Rewired Constants
// This list was generated on 9/22/2020 2:33:04 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Golf
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Golf", friendlyName = "Rotate Yaw")]
        public const int Golf_RotateY = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Golf", friendlyName = "Hit")]
        public const int Golf_Hit = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Golf", friendlyName = "Change Hit Mode")]
        public const int Golf_ChangeHitMode = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Golf", friendlyName = "Toggle Freecam Mode")]
        public const int Golf_ToggleFreecam = 9;
        // Freecam
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Freecam", friendlyName = "Move X")]
        public const int Freecam_MoveX = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Freecam", friendlyName = "Move Y")]
        public const int Freecam_MoveY = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Freecam", friendlyName = "Move Z")]
        public const int Freecam_MoveZ = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Freecam", friendlyName = "Look Y")]
        public const int Freecam_LookY = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Freecam", friendlyName = "Look X")]
        public const int Freecam_LookX = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Freecam", friendlyName = "Boost")]
        public const int Freecam_Boost = 8;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int Golf = 1;
        public const int Freecam = 2;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
